"""
Pulls the public Buttondown RSS feed for idiotswithknifes and rewrites
emails.txt in the same "date / text" format the site already parses
(see the parseEntries() function in index.html and newsletter/index.html).

Run by .github/workflows/sync-emails.yml — do not run manually against
a dirty working tree, it overwrites emails.txt every time.
"""

import re
import urllib.request
import xml.etree.ElementTree as ET
from email.utils import parsedate_to_datetime

RSS_URL = "https://buttondown.com/idiotswithknifes/rss?count=100"
OUTPUT_PATH = "emails.txt"
SUMMARY_MAX_CHARS = 280


def strip_html(raw):
    text = re.sub(r"<[^>]+>", " ", raw or "")
    text = re.sub(r"\s+", " ", text).strip()
    return text


def fetch_feed(url):
    req = urllib.request.Request(url, headers={"User-Agent": "idiotswithknifes-sync/1.0"})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return resp.read()


def parse_items(xml_bytes):
    root = ET.fromstring(xml_bytes)
    entries = []
    for item in root.findall(".//item"):
        title = (item.findtext("title") or "").strip()
        link = (item.findtext("link") or "").strip()
        pub_date_raw = item.findtext("pubDate") or ""
        description = strip_html(item.findtext("description") or "")

        try:
            dt = parsedate_to_datetime(pub_date_raw)
            date_label = dt.strftime("%b %-d, %Y")
        except Exception:
            dt = None
            date_label = pub_date_raw.strip() or "undated"

        summary = description[:SUMMARY_MAX_CHARS].rstrip()
        if len(description) > SUMMARY_MAX_CHARS:
            summary += "…"

        body = f"{title} — {summary}" if title and summary else (title or summary)
        if link:
            body = f"{body} (read: {link})" if body else f"read: {link}"

        if date_label and body:
            entries.append((dt, date_label, body))

    # newest first; entries with an unparseable date sink to the bottom
    from datetime import datetime, timezone
    epoch = datetime.min.replace(tzinfo=timezone.utc)
    entries.sort(key=lambda e: e[0] if e[0] else epoch, reverse=True)
    return entries


def write_output(entries):
    lines = [
        "# AUTO-GENERATED by .github/workflows/sync-emails.yml",
        "# Source: " + RSS_URL,
        "# Do not edit by hand — this file is overwritten on every sync.",
        "",
    ]
    for _, date_label, body in entries:
        lines.append(date_label)
        lines.append(body)
        lines.append("")

    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(lines).rstrip() + "\n")


def main():
    xml_bytes = fetch_feed(RSS_URL)
    entries = parse_items(xml_bytes)
    write_output(entries)
    print(f"Wrote {len(entries)} email(s) to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
