const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Plugins.TiledBg,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Plugins.Text,
		C3.Plugins.CSV,
		C3.Plugins.Json,
		C3.Plugins.Audio,
		C3.Plugins.Button,
		C3.Plugins.progressbar,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Plugins.System.Exps.layoutscale,
		C3.Plugins.progressbar.Acts.SetProgress,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.scrollx,
		C3.Plugins.System.Exps.scrolly,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.progressbar.Acts.SetHeight,
		C3.Plugins.Mouse.Cnds.OnRelease,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Mouse.Acts.SetCursorSprite,
		C3.Behaviors.EightDir.Acts.SetSpeed,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.Button.Acts.Destroy
	];
};
self.C3_JsPropNameTable = [
	{knight: 0},
	{"8Direction": 0},
	{ScrollTo: 0},
	{BoundTo: 0},
	{Player: 0},
	{Mouse: 0},
	{Keyboard: 0},
	{TiledBackground: 0},
	{world_tileset: 0},
	{Bullet: 0},
	{DestroyOutside: 0},
	{Sprite2: 0},
	{Slime: 0},
	{Slime2: 0},
	{Spawn2: 0},
	{Text: 0},
	{Sprite3: 0},
	{bg: 0},
	{Text2: 0},
	{spawner4: 0},
	{Spawn3: 0},
	{Sprite: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Text3: 0},
	{rewards: 0},
	{CSV: 0},
	{JSON: 0},
	{rewards2: 0},
	{rewards3: 0},
	{rewards4: 0},
	{rewards5: 0},
	{rewards6: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Audio: 0},
	{Button3: 0},
	{ProgressBar: 0},
	{Text4: 0},
	{Sprite11: 0},
	{Text5: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{kills: 0},
	{lifes: 0},
	{ammo: 0},
	{zoom: 0},
	{hp: 0},
	{ammopercrate: 0},
	{playsped: 0},
	{rewardleft: 0},
	{rewardleft2: 0}
];

self.InstanceType = {
	knight: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	world_tileset: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Slime: class extends self.ISpriteInstance {},
	Slime2: class extends self.ISpriteInstance {},
	Spawn2: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	bg: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	spawner4: class extends self.ISpriteInstance {},
	Spawn3: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Text3: class extends self.ITextInstance {},
	rewards: class extends self.ITextInstance {},
	CSV: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	rewards2: class extends self.ITextInstance {},
	rewards3: class extends self.ITextInstance {},
	rewards4: class extends self.ITextInstance {},
	rewards5: class extends self.ITextInstance {},
	rewards6: class extends self.ITextInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Button3: class extends self.IButtonInstance {},
	ProgressBar: class extends self.IProgressBarInstance {},
	Text4: class extends self.ITextInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Text5: class extends self.ITextInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {}
}